#pragma once

namespace LauncherLocalization
{
namespace
{
struct ChineseEntry { const char* en; const char* zhHans; const char* zhHant; };
constexpr ChineseEntry CHINESE_ENTRIES[]={
 {"System","系统","系統"},
 {"Language","语言","語言"},
 {"Launcher","启动器","啟動器"},
 {"Settings","设置","設定"},
 {"Game settings","游戏设置","遊戲設定"},
 {"Library & storage","游戏库与存储","遊戲庫與儲存"},
 {"Game folders","游戏文件夹","遊戲資料夾"},
 {"File manager","文件管理器","檔案管理器"},
 {"Install this title?","安装此标题？","安裝此標題？"},
 {"Copy this game to the library?","将此游戏复制到库？","將此遊戲複製到庫？"},
 {"Not installable","无法安装","無法安裝"},
 {"SMB network shares","SMB 网络共享","SMB 網路共用"},
 {"Download covers","下载封面","下載封面"},
 {"Cover settings","封面设置","封面設定"},
 {"Download from SteamGridDB","从 SteamGridDB 下载","從 SteamGridDB 下載"},
 {"Import cover from file","从文件导入封面","從檔案匯入封面"},
 {"Online artwork","在线封面","線上封面"},
 {"Local image","本地图片","本機圖片"},
 {"Search SteamGridDB and replace this game's custom cover with selected online artwork.","在 SteamGridDB 上搜索并用所选在线封面替换此游戏的自定义封面。","在 SteamGridDB 上搜尋並用所選線上封面取代此遊戲的自訂封面。"},
 {"Choose a PNG, JPEG, WebP or BMP image from SD, USB or SMB storage. It is validated and saved safely as PNG.","从 SD、USB 或 SMB 存储中选择 PNG、JPEG、WebP 或 BMP 图片。图片会经验证并安全保存为 PNG。","從 SD、USB 或 SMB 儲存中選擇 PNG、JPEG、WebP 或 BMP 圖片。圖片會經驗證並安全儲存為 PNG。"},
 {"Remove custom cover","移除自定义封面","移除自訂封面"},
 {"Select local cover","选择本地封面","選擇本機封面"},
 {"Cover imported","封面已导入","封面已匯入"},
 {"Custom cover removed","自定义封面已移除","自訂封面已移除"},
 {"Cover import failed","封面导入失败","封面匯入失敗"},
 {"Cover removal failed","封面移除失败","封面移除失敗"},
 {"Remove custom cover?","移除自定义封面？","移除自訂封面？"},
 {"The downloaded or imported cover will be deleted.","已下载或导入的封面将被删除。","已下載或匯入的封面將被刪除。"},
 {"The launcher will use the game's embedded artwork when available.","启动器将在可用时使用游戏内嵌的封面。","啟動器將在可用時使用遊戲內嵌的封面。"},
 {"Search","搜索","搜尋"},
 {"Favorites","收藏","收藏"},
 {"Collections","合集","合集"},
 {"All games","全部游戏","全部遊戲"},
 {"Reset","重置","重設"},
 {"Setting reset to default","设置已重置为默认值","設定已重設為預設值"},
 {"Check for Updates","检查更新","檢查更新"},
 {"SteamGridDB API key","SteamGridDB API 密钥","SteamGridDB API 金鑰"},
 {"Loading game library...","正在加载游戏库...","正在載入遊戲庫..."},
 {"The first page will appear as soon as it is ready.","第一页准备好后会立即显示。","第一頁準備好後會立即顯示。"},
 {"Exit Cemu?","退出 Cemu？","退出 Cemu？"},
 {"Return to the HOME Menu?","返回主页菜单？","返回主頁選單？"},
 {"Closing Cemu...","正在关闭 Cemu...","正在關閉 Cemu..."},
 {"Install","安装","安裝"},
 {"Applet mode installer","小程序模式安装器","小程式模式安裝器"},
 {"Cemu is running in applet mode.","Cemu 正以小程序模式运行。","Cemu 正以小程式模式執行。"},
 {"Install a HOME Menu shortcut to run Cemu with full memory and normal performance.","安装主页菜单快捷方式，以使用完整内存并获得正常性能运行 Cemu。","安裝主頁選單捷徑，以使用完整記憶體並獲得正常效能執行 Cemu。"},
 {"Back","返回","返回"},
 {"Choose","选择","選擇"},
 {"Info","信息","資訊"},
 {"On","开","開"},
 {"Off","关","關"},
 {"Enabled","已启用","已啟用"},
 {"Disabled","已禁用","已停用"},
 {"Change","更改","變更"},
 {"Select","选择","選擇"},
 {"Open","打开","開啟"},
 {"Close","关闭","關閉"},
 {"Cancel","取消","取消"},
 {"Continue","继续","繼續"},
 {"Assign","分配","指派"},
 {"Use artwork","使用艺术图","使用藝術圖"},
 {"Edit / choose","编辑 / 选择","編輯 / 選擇"},
 {"Details / delete","详情 / 删除","詳情 / 刪除"},
 {"Hold to clear","按住清除","按住清除"},
 {"Hold to cancel","按住取消","按住取消"},
 {"Launch","启动","啟動"},
 {"Sort","排序","排序"},
 {"Game Menu","游戏菜单","遊戲選單"},
 {"Filter","筛选","篩選"},
 {"Page","页","頁"},
 {"Quit","退出","退出"},
 {"CPU / Emulation","CPU / 模拟","CPU / 模擬"},
 {"Graphics","图形","圖形"},
 {"Frame Generation","帧生成","幀生成"},
 {"Audio","音频","音訊"},
 {"Overlay","覆盖层","覆蓋層"},
 {"Controller / Input","手柄 / 输入","手把 / 輸入"},
 {"Controller / Input / Accessories","手柄 / 输入 / 配件","手把 / 輸入 / 配件"},
 {"CPU mode","CPU 模式","CPU 模式"},
 {"CPU timer speed","CPU 定时器速度","CPU 計時器速度"},
 {"Hardware video decoding","硬件视频解码","硬體視訊解碼"},
 {"Renderer","渲染器","渲染器"},
 {"Vulkan (NVK)","Vulkan (NVK)","Vulkan (NVK)"},
 {"OpenGL (NVC0)","OpenGL (NVC0)","OpenGL (NVC0)"},
 {"OpenGL (Zink/NVK)","OpenGL (Zink/NVK)","OpenGL (Zink/NVK)"},
 {"Triple buffering","三重缓冲","三重緩衝"},
 {"Async shader compile","异步着色器编译","非同步著色器編譯"},
 {"Accurate barriers (Vulkan)","精确屏障 (Vulkan)","精確屏障 (Vulkan)"},
 {"Upscale filter","放大滤镜","放大濾鏡"},
 {"Downscale filter","缩小滤镜","縮小濾鏡"},
 {"Fullscreen scaling","全屏缩放","全螢幕縮放"},
 {"GamePad screen","GamePad 屏幕","GamePad 螢幕"},
 {"TV volume","TV 音量","TV 音量"},
 {"GamePad audio","GamePad 音频","GamePad 音訊"},
 {"GamePad volume","GamePad 音量","GamePad 音量"},
 {"Audio latency","音频延迟","音訊延遲"},
 {"Flow resolution","光流分辨率","光流解析度"},
 {"Performance mode","性能模式","效能模式"},
 {"FPS counter","FPS 计数器","FPS 計數器"},
 {"Overlay position","覆盖层位置","覆蓋層位置"},
 {"Shader-compile notice","着色器编译通知","著色器編譯通知"},
 {"Console language","主机语言","主機語言"},
 {"Controller type","手柄类型","手把類型"},
 {"Active players","活动玩家","活動玩家"},
 {"Rumble","振动","震動"},
 {"Stick dead zone","摇杆死区","搖桿死區"},
 {"Control mapping","控制映射","控制對應"},
 {"Skylanders Portal","Skylanders 传送门","Skylanders 傳送門"},
 {"Disney Infinity Base","迪士尼无限基座","迪士尼無限基座"},
 {"LEGO Dimensions Toypad","乐高次元玩具板","樂高次元玩具板"},
 {"Theme","主题","主題"},
 {"Games per row","每行游戏数","每列遊戲數"},
 {"Rows per page","每页行数","每頁列數"},
 {"Show game titles","显示游戏标题","顯示遊戲標題"},
 {"Show region flags","显示区域信息","顯示區域信息"},
 {"Show custom settings badges","显示自定义设置徽章","顯示自訂設定徽章"},
 {"UI animations","界面动画","介面動畫"},
 {"Sound effects","音效","音效"},
 {"Check updates at boot","启动时检查更新","開機時檢查更新"},
 {"Online & accounts","在线与账户","線上與帳戶"},
 {"Graphics packs","图形包","圖形包"},
 {"Installed content","已安装内容","已安裝內容"},
 {"missing only","仅缺失项","僅缺失項"},
 {"New collection...","新建合集...","新建合集..."},
 {"Manage collections","管理合集","管理合集"},
 {"Search...","搜索...","搜尋..."},
 {"Favorite","收藏","收藏"},
 {"Rename","重命名","重新命名"},
 {"Copy","复制","複製"},
 {"Move","移动","移動"},
 {"Delete collection","删除合集","刪除合集"},
 {"Filter library","筛选游戏库","篩選遊戲庫"},
 {"Favorites & collections","收藏与合集","收藏與合集"},
 {"Installing...","正在安装...","正在安裝..."},
 {"HOME Menu shortcut installed.","主页菜单快捷方式已安装。","主頁選單捷徑已安裝。"},
 {"Active scans and network operations will be cancelled safely.","活动扫描和网络操作将安全取消。","活動掃描和網路操作將安全取消。"},
 {"Finishing background operations safely.","正在安全完成后台操作。","正在安全完成背景操作。"},
 {"CPU emulation","CPU 模拟","CPU 模擬"},
 {"Game timing / compatibility","游戏时序 / 兼容性","遊戲時序 / 相容性"},
 {"Video playback","视频播放","視訊播放"},
 {"Display backend","显示后端","顯示後端"},
 {"Presentation","呈现","呈現"},
 {"Presentation / performance","呈现 / 性能","呈現 / 效能"},
 {"Shader compilation","着色器编译","著色器編譯"},
 {"Graphics compatibility","图形兼容性","圖形相容性"},
 {"Image scaling","图像缩放","影像縮放"},
 {"Display aspect ratio","显示宽高比","顯示長寬比"},
 {"Wii U GamePad display","Wii U GamePad 显示","Wii U GamePad 顯示"},
 {"Audio output","音频输出","音訊輸出"},
 {"Wii U GamePad audio","Wii U GamePad 音频","Wii U GamePad 音訊"},
 {"Audio latency / stability","音频延迟 / 稳定性","音訊延遲 / 穩定性"},
 {"Frame generation","帧生成","幀生成"},
 {"Frame generation quality","帧生成质量","幀生成品質"},
 {"Frame generation performance","帧生成性能","幀生成效能"},
 {"Performance display","性能显示","效能顯示"},
 {"Emulated controller","模拟手柄","模擬手把"},
 {"Controller input","手柄输入","手把輸入"},
 {"Controller feedback","手柄反馈","手把回饋"},
 {"Analog input","模拟输入","類比輸入"},
 {"Emulated USB accessory","模拟 USB 配件","模擬 USB 配件"},
 {"Wii U system language","Wii U 系统语言","Wii U 系統語言"},
 {"Launcher appearance","启动器外观","啟動器外觀"},
 {"Launcher language","启动器语言","啟動器語言"},
 {"Library layout","游戏库布局","遊戲庫版面"},
 {"Launcher audio","启动器音频","啟動器音訊"},
 {"Launcher updates","启动器更新","啟動器更新"},
 {"Controller mapping","手柄映射","手把對應"},
 {"Required component","必需组件","必要元件"},
 {"Setting","设置","設定"},
 {"Per-game setting","按游戏设置","依遊戲設定"},
 {"Global setting","全局设置","全域設定"},
 {"Launcher setting","启动器设置","啟動器設定"},
 {"Launcher action","启动器操作","啟動器動作"},
 {"Settings category","设置类别","設定類別"},
 {"Per-game overrides","按游戏覆盖","依遊戲覆寫"},
 {"Selects how Cemu executes the Wii U CPU. The multi-core recompiler is fastest on Switch. Use single-core only for compatibility testing; the interpreter is extremely slow and intended for debugging.","选择 Cemu 如何执行 Wii U CPU。多核重编译器在 Switch 上最快。仅在兼容性测试时使用单核，该模式运行效率极慢，仅用于调试。","選擇 Cemu 如何執行 Wii U CPU。多核重編譯器在 Switch 上最快。僅在相容性測試時使用單核，該模式運行效率極慢，僅用於除錯。"},
 {"Changes the speed of the emulated CPU timer without increasing the Switch CPU clock. Some game-specific fixes need a different timer rate, but the normal 1x value is the safest default.","更改模拟 CPU 定时器速度而不提高 Switch CPU 时钟。某些游戏特定修复需要不同定时器速率，但正常的 1x 值是最安全的默认值。","變更模擬 CPU 計時器速度而不提高 Switch CPU 時鐘。某些遊戲特定修復需要不同計時器速率，但正常的 1x 值是最安全的預設值。"},
 {"Uses the Switch hardware video decoder for Wii U H.264 movies. Disable it only when troubleshooting broken or missing in-game video playback.","使用 Switch 硬件视频解码器播放 Wii U H.264 影片。仅在排查游戏内视频播放损坏或缺失时禁用。","使用 Switch 硬體視訊解碼器播放 Wii U H.264 影片。僅在排查遊戲內視訊播放損壞或缺失時停用。"},
 {"Chooses the graphics backend in the unified Cemu core. Vulkan (NVK) is recommended and is required by LSFG. OpenGL uses native NVC0, while Zink runs Cemu's OpenGL renderer on NVK as an additional compatibility path.","选择统一 Cemu 核心中的图形后端。推荐 Vulkan (NVK)，且 LSFG 需要它。OpenGL 使用原生 NVC0，而 Zink 在 NVK 上运行 Cemu 的 OpenGL 渲染器作为额外兼容路径。","選擇統一 Cemu 核心中的圖形後端。推薦 Vulkan (NVK)，且 LSFG 需要它。OpenGL 使用原生 NVC0，而 Zink 在 NVK 上執行 Cemu 的 OpenGL 渲染器作為額外相容路徑。"},
 {"Synchronizes completed frames to the display refresh to reduce tearing. It can add latency or expose performance drops when a game cannot maintain its target frame rate.","将完成的帧与显示器刷新同步以减少撕裂。当游戏无法维持目标帧率时，可能增加延迟或暴露性能下降。","將完成的幀與顯示器重新整理同步以減少撕裂。當遊戲無法維持目標幀率時，可能增加延遲或暴露效能下降。"},
 {"Keeps a third Vulkan swapchain image available while another frame is being displayed. This can make presentation steadier under load, at the cost of some memory and potentially more latency.","在显示另一帧时保持第三个 Vulkan 交换链图像可用。这可使负载下呈现更稳定，但会消耗一些内存并可能增加延迟。","在顯示另一幀時保持第三個 Vulkan 交換鏈影像可用。這可使負載下呈現更穩定，但會消耗一些記憶體並可能增加延遲。"},
 {"Compiles Vulkan shaders asynchronously to reduce long gameplay stalls. Newly encountered effects may be missing briefly while their shaders finish compiling.","异步编译 Vulkan 着色器以减少长时间游戏卡顿。新遇到的效果可能在其着色器完成编译前短暂缺失。","非同步編譯 Vulkan 著色器以減少長時間遊戲卡頓。新遇到的效果可能在其著色器完成編譯前短暫缺失。"},
 {"Uses more accurate Vulkan synchronization between rendering operations. Keep it enabled for correct effects; disabling it may improve performance slightly but can cause game-specific rendering errors.","在渲染操作之间使用更精确的 Vulkan 同步。为正确效果请保持启用；禁用可能略微提升性能但可能导致游戏特定渲染错误。","在渲染操作之間使用更精確的 Vulkan 同步。為正確效果請保持啟用；停用可能略微提升效能但可能導致遊戲特定渲染錯誤。"},
 {"Selects the filter used when the Wii U image is enlarged to the Switch display. Nearest is sharp and pixelated, while the other filters trade sharpness for smoother scaling.","选择将 Wii U 图像放大到 Switch 显示时使用的滤镜。最近邻锐利且有像素感，其他滤镜以锐度为代价换取更平滑缩放。","選擇將 Wii U 影像放大到 Switch 顯示時使用的濾鏡。最近鄰銳利且有像素感，其他濾鏡以銳度為代價換取更平滑縮放。"},
 {"Selects the filter used when an image must be reduced. The choice changes sharpness and aliasing but does not change the game's internal rendering resolution.","选择必须缩小图像时使用的滤镜。选择会改变锐度和锯齿，但不改变游戏内部渲染分辨率。","選擇必須縮小影像時使用的濾鏡。選擇會改變銳度和鋸齒，但不改變遊戲內部渲染解析度。"},
 {"Keep aspect ratio preserves the game's intended shape and may leave borders. Stretch fills the output but can distort the image.","保持宽高比保留游戏预期形状并可能留下边框。拉伸填满输出但可能扭曲图像。","保持長寬比保留遊戲預期形狀並可能留下邊框。拉伸填滿輸出但可能扭曲影像。"},
 {"Chooses whether to show the TV view, the GamePad view, or both views in a split layout. Composite layouts reduce the space available to each screen.","选择显示 TV 视图、GamePad 视图或两者分屏布局。组合布局会减少每个屏幕可用空间。","選擇顯示 TV 視圖、GamePad 視圖或兩者分割版面。組合版面會減少每個螢幕可用空間。"},
 {"Sets the volume of the emulated Wii U TV audio stream sent to the Switch output.","设置发送到 Switch 输出的模拟 Wii U TV 音频流音量。","設定發送到 Switch 輸出的模擬 Wii U TV 音訊流音量。"},
 {"Enables the separate audio stream that Wii U software sends to the GamePad. Disable it when duplicated TV and GamePad sound is unwanted.","启用 Wii U 软件发送到 GamePad 的独立音频流。当不希望 TV 和 GamePad 声音重复时禁用。","啟用 Wii U 軟體發送到 GamePad 的獨立音訊流。當不希望 TV 和 GamePad 聲音重複時停用。"},
 {"Sets the volume of the emulated GamePad audio stream when GamePad audio is enabled.","在启用 GamePad 音频时设置模拟 GamePad 音频流的音量。","在啟用 GamePad 音訊時設定模擬 GamePad 音訊流的音量。"},
 {"Controls Cemu's audio buffer target. Lower values reduce latency but can crackle when emulation is uneven; higher values are more stable but respond later.","控制 Cemu 的音频缓冲区目标。较低值减少延迟，但在模拟不稳定时可能产生爆音；较高值更稳定但响应更晚。","控制 Cemu 的音訊緩衝區目標。較低值減少延遲，但在模擬不穩定時可能產生爆音；較高值更穩定但回應更晚。"},
 {"Generates one intermediate display frame for each real frame to target a smoother 2x presentation. It does not increase emulation speed and may add artifacts or latency. Vulkan only.","为每个真实帧生成一个中间显示帧以实现更平滑的 2x 呈现。不会提高模拟速度，可能增加伪影或延迟。仅限 Vulkan。","為每個真實幀生成一個中間顯示幀以實現更平滑的 2x 呈現。不會提高模擬速度，可能增加偽影或延遲。僅限 Vulkan。"},
 {"Sets the resolution used for optical-flow analysis. Half resolution can retain more motion detail but costs more GPU time and memory; Quarter is recommended on Switch.","设置光流分析使用的分辨率。半分辨率可保留更多运动细节但消耗更多 GPU 时间和内存；在 Switch 上推荐四分之一。","設定光流分析使用的解析度。半解析度可保留更多運動細節但消耗更多 GPU 時間和記憶體；在 Switch 上推薦四分之一。"},
 {"Uses LSFG's lighter performance-oriented processing path. Disable it only when you prefer image quality and have enough GPU headroom.","使用 LSFG 更轻量的性能导向处理路径。仅在优先图像质量且有足够 GPU 余量时禁用。","使用 LSFG 更輕量的效能導向處理路徑。僅在優先影像品質且有足夠 GPU 餘量時停用。"},
 {"Shows Cemu's frame-rate counter during gameplay.","在游戏过程中显示 Cemu 的帧率计数器。","在遊戲過程中顯示 Cemu 的幀率計數器。"},
 {"Chooses where Cemu's on-screen performance overlay is drawn. Disabled hides the overlay and its FPS counter.","选择 Cemu 屏幕性能覆盖层的绘制位置。禁用会隐藏覆盖层及其 FPS 计数器。","選擇 Cemu 螢幕效能覆蓋層的繪製位置。停用會隱藏覆蓋層及其 FPS 計數器。"},
 {"Shows a notification while Cemu is compiling shaders so brief stutter or temporarily missing effects can be identified.","在 Cemu 编译着色器时显示通知，以便识别短暂卡顿或暂时缺失的效果。","在 Cemu 編譯著色器時顯示通知，以便識別短暫卡頓或暫時缺失的效果。"},
 {"Selects the Wii U controller type presented to the game. Wii U GamePad is required by games that use its screen, microphone, or touch features.","选择呈现给游戏的 Wii U 手柄类型。使用屏幕、麦克风或触摸功能的游戏需要 Wii U GamePad。","選擇呈現給遊戲的 Wii U 手把類型。使用螢幕、麥克風或觸控功能的遊戲需要 Wii U GamePad。"},
 {"Sets how many active emulated controller slots Cemu creates for local multiplayer.","设置 Cemu 为本地多人游戏创建的活动模拟手柄插槽数量。","設定 Cemu 為本機多人遊戲建立的活動模擬手把插槽數量。"},
 {"Forwards supported Wii U controller vibration effects to the connected Switch controller.","将支持的 Wii U 手柄振动效果转发到已连接的 Switch 手柄。","將支援的 Wii U 手把震動效果轉發到已連接的 Switch 手把。"},
 {"Sets how far an analog stick must move before Cemu accepts input. Raise it to prevent drift; lower it for quicker response.","设置模拟摇杆在 Cemu 接受输入前必须移动的距离。提高以防止漂移；降低以获得更快响应。","設定類比搖桿在 Cemu 接受輸入前必須移動的距離。提高以防止漂移；降低以獲得更快回應。"},
 {"Enables Cemu's virtual Skylanders Portal for games that communicate with that USB accessory.","为与该 USB 配件通信的游戏启用 Cemu 的虚拟 Skylanders 传送门。","為與該 USB 配件通訊的遊戲啟用 Cemu 的虛擬 Skylanders 傳送門。"},
 {"Enables Cemu's virtual Disney Infinity Base for games that communicate with that USB accessory.","为与该 USB 配件通信的游戏启用 Cemu 的虚拟迪士尼无限基座。","為與該 USB 配件通訊的遊戲啟用 Cemu 的虛擬迪士尼無限基座。"},
 {"Enables Cemu's virtual LEGO Dimensions Toy Pad for games that communicate with that USB accessory.","为与该 USB 配件通信的游戏启用 Cemu 的虚拟乐高次元玩具板。","為與該 USB 配件通訊的遊戲啟用 Cemu 的虛擬樂高次元玩具板。"},
 {"Sets the language reported by the emulated Wii U console. Auto follows the Switch system language when Cemu supports it; games may need to be restarted after a change.","设置模拟 Wii U 主机报告的语言。自动在 Cemu 支持时跟随 Switch 系统语言；更改后可能需要重启游戏。","設定模擬 Wii U 主機報告的語言。自動在 Cemu 支援時跟隨 Switch 系統語言；變更後可能需要重新啟動遊戲。"},
 {"Changes the SDL launcher's background and visual theme. It does not affect gameplay rendering.","更改 SDL 启动器的背景和视觉主题。不影响游戏渲染。","變更 SDL 啟動器的背景和視覺主題。不影響遊戲渲染。"},
 {"Selects the language used by the SDL launcher. System follows the Switch console language; technical emulator names and identifiers remain unchanged for accuracy.","选择 SDL 启动器使用的语言。系统跟随 Switch 主机语言；技术模拟器名称和标识符为准确性保持不变。","選擇 SDL 啟動器使用的語言。系統跟隨 Switch 主機語言；技術模擬器名稱和識別碼為準確性保持不變。"},
 {"Sets how many game covers are displayed across each library row. More columns make each cover smaller.","设置游戏库每行显示的封面数量。更多列会使每个封面更小。","設定遊戲庫每列顯示的封面數量。更多欄會使每個封面更小。"},
 {"Sets how many rows of game covers are displayed on each library page. More rows make each cover smaller.","设置游戏库每页显示的封面行数。更多行会使每个封面更小。","設定遊戲庫每頁顯示的封面列數。更多列會使每個封面更小。"},
 {"Shows or hides game names below their cover artwork in the launcher library.","在启动器游戏库中显示或隐藏封面艺术图下方的游戏名称。","在啟動器遊戲庫中顯示或隱藏封面藝術圖下方的遊戲名稱。"},
 {"Shows or hides the region flag in the top-left corner of each game cover.","显示或隐藏每个游戏封面左上角的区域标识。","顯示或隱藏每個遊戲封面左上角的區域標識。"},
 {"Shows or hides the square badge on games that have per-game settings. The settings themselves are not changed.","显示或隐藏有按游戏设置的游戏上的方形徽章。设置本身不会更改。","顯示或隱藏有依遊戲設定的遊戲上的方形徽章。設定本身不會變更。"},
 {"Enables launcher transitions, moving highlights, and animated theme effects.","启用启动器过渡、移动高亮和动画主题效果。","啟用啟動器過渡、移動醒目提示和動畫主題效果。"},
 {"Enables navigation, confirmation, and back sound effects in the SDL launcher.","在 SDL 启动器中启用导航、确认和返回音效。","在 SDL 啟動器中啟用導覽、確認和返回音效。"},
 {"Checks for a newer Cemu-nx release when the SDL launcher starts. The result appears in Launcher settings.","在 SDL 启动器启动时检查较新的 Cemu-nx 版本。并将结果显示在启动器设置中。","在 SDL 啟動器啟動時檢查較新的 Cemu-nx 版本。并將結果顯示在啟動器設定中。"},
 {"Opens the press-to-bind screen for every Wii U controller input. Select a control, then press the Switch button or trigger that should activate it.","打开每个 Wii U 手柄输入的按键绑定屏幕。选择一个控制，然后按下应激活它的 Switch 按钮或扳机。","開啟每個 Wii U 手把輸入的按鍵綁定螢幕。選擇一個控制，然後按下應啟用它的 Switch 按鈕或扳機。"},
 {"Shows whether the Lossless Scaling frame-generation library is installed. LSFG cannot be enabled until Lossless.dll is copied to sdmc:/switch/cemu/lsfg/.","显示 Lossless Scaling 帧生成库是否已安装。在将 Lossless.dll 复制到 sdmc:/switch/cemu/lsfg/ 之前无法启用 LSFG。","顯示 Lossless Scaling 幀生成庫是否已安裝。在將 Lossless.dll 複製到 sdmc:/switch/cemu/lsfg/ 之前無法啟用 LSFG。"},
 {" cache file(s) could not be removed."," 个缓存文件无法移除。"," 個快取檔案無法移除。"},
 {"A SteamGridDB API key is required","需要 SteamGridDB API 密钥","需要 SteamGridDB API 金鑰"},
 {"Account","账户","帳戶"},
 {"Account used by the SMB server. Leave blank for guest access.","SMB 服务器使用的账户。留空以访客访问。","SMB 伺服器使用的帳戶。留空以訪客存取。"},
 {"Add network_services.xml to the Cemu directory.","将 network_services.xml 添加到 Cemu 目录。","將 network_services.xml 新增到 Cemu 目錄。"},
 {"Add the key to sdmc:/switch/cemu/keys.txt.","将密钥添加到 sdmc:/switch/cemu/keys.txt。","將金鑰新增到 sdmc:/switch/cemu/keys.txt。"},
 {"All covers already downloaded","所有封面已下载","所有封面已下載"},
 {"All folders are scanned and passed to Cemu","所有文件夹均已扫描并传递给 Cemu","所有資料夾均已掃描並傳遞給 Cemu"},
 {"Already in the games folder","已在游戏文件夹中","已在遊戲資料夾中"},
 {"An item with that name already exists.","已存在同名项目。","已存在同名項目。"},
 {"Artwork search failed","艺术图搜索失败","藝術圖搜尋失敗"},
 {"Building + installing forwarder...","正在构建并安装转发器...","正在建置並安裝轉發器..."},
 {"Cache cleanup failed","缓存清理失败","快取清理失敗"},
 {"Cancelling...","正在取消...","正在取消..."},
 {"Cemu Update","Cemu 更新","Cemu 更新"},
 {"Cemu configuration could not be updated safely.","无法安全更新 Cemu 配置。","無法安全更新 Cemu 組態。"},
 {"Cemu will rebuild them the next time the game runs.","Cemu 将在下次运行游戏时重建它们。","Cemu 將在下次執行遊戲時重建它們。"},
 {"Cemu/keys.txt does not contain a Wii U disc key.","Cemu/keys.txt 不包含 Wii U 光盘密钥。","Cemu/keys.txt 不包含 Wii U 光碟金鑰。"},
 {"Check free SD space and file permissions.","检查可用 SD 空间和文件权限。","檢查可用 SD 空間和檔案權限。"},
 {"Check the connection and try again.","检查连接并重试。","檢查連線並重試。"},
 {"Choose an icon","选择图标","選擇圖示"},
 {"Choose another destination or rename the folder first.","选择其他目标或先重命名文件夹。","選擇其他目的地或先重新命名資料夾。"},
 {"Choose cover artwork","选择封面艺术图","選擇封面藝術圖"},
 {"Choose matching title","选择匹配标题","選擇相符標題"},
 {"Clear shader caches?","清除着色器缓存？","清除著色器快取？"},
 {"Close files using this drive before ejecting.","弹出前请关闭使用此驱动器的文件。","退出前請關閉使用此磁碟機的檔案。"},
 {"Collection already exists","合集已存在","合集已存在"},
 {"Collection name","合集名称","合集名稱"},
 {"Connecting USB storage","正在连接 USB 存储","正在連接 USB 儲存"},
 {"Connection preview","连接预览","連線預覽"},
 {"Control assigned","控制已分配","控制已指派"},
 {"Copied to clipboard","已复制到剪贴板","已複製到剪貼簿"},
 {"Copy an existing Wii U account.dat into:","将现有 Wii U account.dat 复制到：","將現有 Wii U account.dat 複製到："},
 {"Copy it to sdmc:/switch/cemu/lsfg/Lossless.dll","将其复制到 sdmc:/switch/cemu/lsfg/Lossless.dll","將其複製到 sdmc:/switch/cemu/lsfg/Lossless.dll"},
 {"Could not check destination","无法检查目标","無法檢查目的地"},
 {"Could not create games folder","无法创建游戏文件夹","無法建立遊戲資料夾"},
 {"Could not install the emulator to the SD card.","无法将模拟器安装到 SD 卡。","無法將模擬器安裝到 SD 卡。"},
 {"Could not preserve the existing destination.","无法保留现有目标。","無法保留現有目的地。"},
 {"Could not recover previous install","无法恢复先前安装","無法復原先前安裝"},
 {"Could not save graphics packs","无法保存图形包","無法儲存圖形包"},
 {"Cover download failed","封面下载失败","封面下載失敗"},
 {"Cover downloaded","封面已下载","封面已下載"},
 {"Cover search failed","封面搜索失败","封面搜尋失敗"},
 {"Create HOME shortcut","创建主页快捷方式","建立主頁捷徑"},
 {"Create shortcut","创建快捷方式","建立捷徑"},
 {"Creating HOME shortcut","正在创建主页快捷方式","正在建立主頁捷徑"},
 {"Credential readiness","凭证就绪","認證就緒"},
 {"Custom SteamGridDB search","自定义 SteamGridDB 搜索","自訂 SteamGridDB 搜尋"},
 {"Custom service needs configuration","自定义服务需要配置","自訂服務需要組態"},
 {"Delete collection?","删除合集？","刪除合集？"},
 {"Delete failed","删除失败","刪除失敗"},
 {"Delete game?","删除游戏？","刪除遊戲？"},
 {"Destination is not a file","目标不是文件","目的地不是檔案"},
 {"Disc key required","需要光盘密钥","需要光碟金鑰"},
 {"Display name required","需要显示名称","需要顯示名稱"},
 {"Do not include a drive letter or smb:// prefix.","不要包含驱动器号或 smb:// 前缀。","不要包含磁碟機代號或 smb:// 前置詞。"},
 {"Download latest packs","下载最新包","下載最新包"},
 {"Downloading latest graphic packs...","正在下载最新图形包...","正在下載最新圖形包..."},
 {"Downloading selected cover...","正在下载所选封面...","正在下載所選封面..."},
 {"Edit / toggle","编辑 / 切换","編輯 / 切換"},
 {"Emulator missing - copy cemu.nro into sdmc:/switch/cemu/","模拟器缺失 - 将 cemu.nro 复制到 sdmc:/switch/cemu/","模擬器缺失 - 將 cemu.nro 複製到 sdmc:/switch/cemu/"},
 {"Emulator setup failed","模拟器设置失败","模擬器設定失敗"},
 {"Preparing emulator...","正在准备模拟器...","正在準備模擬器..."},
 {"The embedded Cemu core could not be prepared.","无法准备嵌入式 Cemu 核心。","無法準備嵌入式 Cemu 核心。"},
 {"The SD card may be full or write-protected.","SD 卡可能已满或写保护。","SD 卡可能已滿或寫入保護。"},
 {"Free some space and try launching the game again.","释放一些空间并再次尝试启动游戏。","釋放一些空間並再次嘗試啟動遊戲。"},
 {"Enter a name used to identify this share in Cemu.","输入用于在 Cemu 中识别此共享的名称。","輸入用於在 Cemu 中識別此共用的名稱。"},
 {"Enter a share name, optionally followed by folders.","输入共享名称，可选后跟文件夹。","輸入共用名稱，可選後接資料夾。"},
 {"Enter only a host name or IP address.","仅输入主机名或 IP 地址。","僅輸入主機名稱或 IP 位址。"},
 {"Enter the network host only. Do not include smb:// or a folder.","仅输入网络主机。不要包含 smb:// 或文件夹。","僅輸入網路主機。不要包含 smb:// 或資料夾。"},
 {"Enter the share and an optional folder path inside it.","输入共享及其中的可选文件夹路径。","輸入共用及其中的可選資料夾路徑。"},
 {"Example: 192.168.1.20","示例：192.168.1.20","範例：192.168.1.20"},
 {"Example: 192.168.1.20 or NAS.local","示例：192.168.1.20 或 NAS.local","範例：192.168.1.20 或 NAS.local"},
 {"Example: Living room NAS","示例：客厅 NAS","範例：客廳 NAS"},
 {"Example: WORKGROUP, or leave blank","示例：WORKGROUP，或留空","範例：WORKGROUP，或留空"},
 {"Extracted game folders are not deleted automatically.","提取的游戏文件夹不会自动删除。","提取的遊戲資料夾不會自動刪除。"},
 {"Fetching icons from SteamGridDB...","正在从 SteamGridDB 获取图标...","正在從 SteamGridDB 取得圖示..."},
 {"File options","文件选项","檔案選項"},
 {"File transfer","文件传输","檔案傳輸"},
 {"Folder already added","文件夹已添加","資料夾已新增"},
 {"Folder already exists","文件夹已存在","資料夾已存在"},
 {"Folder deletion disabled","文件夹删除已禁用","資料夾刪除已停用"},
 {"Folder unavailable","文件夹不可用","資料夾無法使用"},
 {"Free up space and relaunch.","释放空间并重新启动。","釋放空間並重新啟動。"},
 {"Friendly name shown in the Cemu file browser.","在 Cemu 文件浏览器中显示的友好名称。","在 Cemu 檔案瀏覽器中顯示的友善名稱。"},
 {"Game deleted","游戏已删除","遊戲已刪除"},
 {"Game folder","游戏文件夹","遊戲資料夾"},
 {"Game not found","未找到游戏","找不到遊戲"},
 {"Game settings cleared","游戏设置已清除","遊戲設定已清除"},
 {"Games path is not a folder","游戏路径不是文件夹","遊戲路徑不是資料夾"},
 {"HOME shortcut installed","主页快捷方式已安装","主頁捷徑已安裝"},
 {"Imported Wii U account","已导入 Wii U 账户","已匯入 Wii U 帳戶"},
 {"Installed component","已安装组件","已安裝元件"},
 {"Installed component deleted","已安装组件已删除","已安裝元件已刪除"},
 {"Installing title...","正在安装标题...","正在安裝標題..."},
 {"Invalid SMB server","无效的 SMB 服务器","無效的 SMB 伺服器"},
 {"Invalid SMB share","无效的 SMB 共享","無效的 SMB 共用"},
 {"Invalid name","无效名称","無效名稱"},
 {"LSFG 2x / Vulkan","LSFG 2x / Vulkan","LSFG 2x / Vulkan"},
 {"LSFG disabled for this launch","本次启动已禁用 LSFG","本次啟動已停用 LSFG"},
 {"LSFG is not ready","LSFG 未就绪","LSFG 未就緒"},
 {"Launch configuration failed","启动配置失败","啟動組態失敗"},
 {"Leave blank for guest","留空以访客身份","留空以訪客身份"},
 {"Leave blank when no password is required","不需要密码时留空","不需要密碼時留空"},
 {"Loading available artwork...","正在加载可用艺术图...","正在載入可用藝術圖..."},
 {"Loading preview...","正在加载预览...","正在載入預覽..."},
 {"Location unavailable","位置不可用","位置無法使用"},
 {"Lossless.dll was not found at","未在以下位置找到 Lossless.dll","未在以下位置找到 Lossless.dll"},
 {"Lossless.dll was not found.","未找到 Lossless.dll。","未找到 Lossless.dll。"},
 {"Maximum of 16 game folders","最多 16 个游戏文件夹","最多 16 個遊戲資料夾"},
 {"Maximum of 24 pinned folders","最多 24 个固定文件夹","最多 24 個釘選資料夾"},
 {"Maximum of 8 SMB shares","最多 8 个 SMB 共享","最多 8 個 SMB 共用"},
 {"Metadata missing or does not match the title ID","元数据缺失或与标题 ID 不匹配","中繼資料缺失或與標題 ID 不符"},
 {"Metadata verified","元数据已验证","中繼資料已驗證"},
 {"Move complete","移动完成","移動完成"},
 {"Move failed","移动失败","移動失敗"},
 {"Move incomplete","移动未完成","移動未完成"},
 {"Move queued","移动已排队","移動已排隊"},
 {"Names cannot contain /, \\\\, :, or control characters.","名称不能包含 /、\\、: 或控制字符。","名稱不能包含 /、\\、: 或控制字元。"},
 {"Nested folders are supported.","支持嵌套文件夹。","支援巢狀資料夾。"},
 {"Network service","网络服务","網路服務"},
 {"No","否","否"},
 {"No controller is connected.","未连接手柄。","未連接手把。"},
 {"No files will be deleted.","不会删除任何文件。","不會刪除任何檔案。"},
 {"No games will be deleted.","不会删除任何游戏。","不會刪除任何遊戲。"},
 {"No icon found - add a SteamGridDB key or download a cover first","未找到图标 - 请先添加 SteamGridDB 密钥或下载封面","找不到圖示 - 請先新增 SteamGridDB 金鑰或下載封面"},
 {"No imported accounts","无已导入账户","無已匯入帳戶"},
 {"No metadata was removed.","未移除任何元数据。","未移除任何中繼資料。"},
 {"No packs available for this game","此游戏无可用图形包","此遊戲無可用圖形包"},
 {"No shader caches found","未找到着色器缓存","找不到著色器快取"},
 {"Not enough free space","可用空间不足","可用空間不足"},
 {"Not found","未找到","找不到"},
 {"Offline / Nintendo / Pretendo","离线 / Nintendo / Pretendo","離線 / Nintendo / Pretendo"},
 {"Offline / Nintendo / Pretendo / Custom","离线 / Nintendo / Pretendo / 自定义","離線 / Nintendo / Pretendo / 自訂"},
 {"Online services require an imported account.dat.","在线服务需要已导入的 account.dat。","線上服務需要已匯入的 account.dat。"},
 {"Online settings unavailable","在线设置不可用","線上設定無法使用"},
 {"Open Settings > Launcher > Check for Updates","打开设置 > 启动器 > 检查更新","開啟設定 > 啟動器 > 檢查更新"},
 {"Password","密码","密碼"},
 {"Password for the SMB account. It is stored in launcher.ini.","SMB 账户的密码。存储在 launcher.ini 中。","SMB 帳戶的密碼。儲存在 launcher.ini 中。"},
 {"Paste failed","粘贴失败","貼上失敗"},
 {"Pick an icon first","请先选择图标","請先選擇圖示"},
 {"Press the button or trigger to assign","按下按钮或扳机以分配","按下按鈕或扳機以指派"},
 {"Press-to-bind","按键绑定","按鍵綁定"},
 {"Preview unavailable","预览不可用","預覽無法使用"},
 {"Reconnect its storage or update the game folders.","重新连接其存储或更新游戏文件夹。","重新連接其儲存或更新遊戲資料夾。"},
 {"Release the current button","松开当前按钮","放開目前按鈕"},
 {"Remove SMB share?","移除 SMB 共享？","移除 SMB 共用？"},
 {"Remove game folder?","移除游戏文件夹？","移除遊戲資料夾？"},
 {"Remove this folder manually to avoid deleting unrelated files:","手动移除此文件夹以避免删除无关文件：","手動移除此資料夾以避免刪除無關檔案："},
 {"Rename collection","重命名合集","重新命名合集"},
 {"Rename failed","重命名失败","重新命名失敗"},
 {"Rename game","重命名游戏","重新命名遊戲"},
 {"Renamed","已重命名","已重新命名"},
 {"Replace existing file?","替换现有文件？","取代現有檔案？"},
 {"Review both locations before trying again.","重试前请检查两个位置。","重試前請檢查兩個位置。"},
 {"SMB connection failed","SMB 连接失败","SMB 連線失敗"},
 {"SMB display name","SMB 显示名称","SMB 顯示名稱"},
 {"Safely eject USB drive?","安全弹出 USB 驱动器？","安全退出 USB 磁碟機？"},
 {"Saved data was not touched.","存档数据未受影响。","存檔資料未受影響。"},
 {"Saved folders on this share will also be removed.","此共享上的已保存文件夹也将被移除。","此共用上的已儲存資料夾也將被移除。"},
 {"Search games","搜索游戏","搜尋遊戲"},
 {"Searching SteamGridDB...","正在搜索 SteamGridDB...","正在搜尋 SteamGridDB..."},
 {"Select a control","选择一个控制","選擇一個控制"},
 {"Select an account first","请先选择账户","請先選擇帳戶"},
 {"Selecting a service does not create credentials or guarantee server access.","选择服务不会创建凭证或保证服务器访问。","選擇服務不會建立認證或保證伺服器存取。"},
 {"Server or IP address","服务器或 IP 地址","伺服器或 IP 位址"},
 {"Service","服务","服務"},
 {"Settings not saved","设置未保存","設定未儲存"},
 {"Shader caches cleared","着色器缓存已清除","著色器快取已清除"},
 {"Shared folder","共享文件夹","共用資料夾"},
 {"Shortcut failed","快捷方式失败","捷徑失敗"},
 {"SteamGridDB API key rejected","SteamGridDB API 密钥被拒绝","SteamGridDB API 金鑰被拒絕"},
 {"The copied item is no longer available.","复制的项目不再可用。","複製的項目不再可用。"},
 {"The copy completed, but the original could not be removed completely.","复制完成，但原始文件无法完全移除。","複製完成，但原始檔案無法完全移除。"},
 {"The destination cannot be inside the source.","目标不能位于源内部。","目的地不能位於來源內部。"},
 {"The destination does not have enough available space.","目标没有足够可用空间。","目的地沒有足夠可用空間。"},
 {"The destination is not a regular file.","目标不是常规文件。","目的地不是一般檔案。"},
 {"The device may be disconnected.","设备可能已断开连接。","裝置可能已中斷連線。"},
 {"The existing copy will be replaced.","现有副本将被替换。","現有副本將被取代。"},
 {"The existing file will be replaced.","现有文件将被替换。","現有檔案將被取代。"},
 {"The file transfer could not be completed.","文件传输无法完成。","檔案傳輸無法完成。"},
 {"The game file could not be removed.","无法移除游戏文件。","無法移除遊戲檔案。"},
 {"The game will start automatically","游戏将自动启动","遊戲將自動啟動"},
 {"The installed launcher was left unchanged.","已安装的启动器保持不变。","已安裝的啟動器保持不變。"},
 {"The launcher could not initialize its network connection.","启动器无法初始化其网络连接。","啟動器無法初始化其網路連線。"},
 {"The previous settings were preserved.","先前的设置已保留。","先前的設定已保留。"},
 {"The selected game no longer exists.","所选游戏不再存在。","所選遊戲不再存在。"},
 {"The selected path is not a regular game file.","所选路径不是常规游戏文件。","所選路徑不是一般遊戲檔案。"},
 {"The service remains offline until that file is present.","在该文件存在之前，服务保持离线。","在該檔案存在之前，服務保持離線。"},
 {"The shortcut's game is not in the current library.","快捷方式的游戏不在当前游戏库中。","捷徑的遊戲不在目前遊戲庫中。"},
 {"This permanently deletes the game file from","这将永久从以下位置删除游戏文件：","這將永久從以下位置刪除遊戲檔案："},
 {"Touch anywhere to close","触摸任意处关闭","觸控任意處關閉"},
 {"Touch left to clear       Touch right to cancel","触摸左侧清除       触摸右侧取消","觸控左側清除       觸控右側取消"},
 {"Transfer cancelled","传输已取消","傳輸已取消"},
 {"Transfer complete","传输完成","傳輸完成"},
 {"Transfer failed","传输失败","傳輸失敗"},
 {"USB drive can now be removed","现在可以移除 USB 驱动器","現在可以移除 USB 磁碟機"},
 {"USB eject failed","USB 弹出失败","USB 退出失敗"},
 {"Unknown error","未知错误","未知錯誤"},
 {"Unnamed Wii U title","未命名 Wii U 标题","未命名 Wii U 標題"},
 {"Update check unavailable","更新检查不可用","更新檢查無法使用"},
 {"Update recovery failed","更新恢复失败","更新復原失敗"},
 {"Update the saved API key in Launcher settings.","在启动器设置中更新已保存的 API 密钥。","在啟動器設定中更新已儲存的 API 金鑰。"},
 {"Username","用户名","使用者名稱"},
 {"Usually optional on a home network.","在家庭网络上通常可选。","在家庭網路上通常可選。"},
 {"WUX games cannot be decrypted until a valid key is added.","在添加有效密钥之前无法解密 WUX 游戏。","在新增有效金鑰之前無法解密 WUX 遊戲。"},
 {"Waiting for the game drive...","正在等待游戏驱动器...","正在等待遊戲磁碟機..."},
 {"Workgroup","工作组","工作群組"},
 {"Yes","是","是"},
 {"[ Add SMB share ]","[ 添加 SMB 共享 ]","[ 新增 SMB 共用 ]"},
 {"browse / download","浏览 / 下载","瀏覽 / 下載"},
 {"games / files / network","游戏 / 文件 / 网络","遊戲 / 檔案 / 網路"},
 {"settings.xml could not be read safely.","无法安全读取 settings.xml。","無法安全讀取 settings.xml。"},
 {"settings.xml could not be updated safely.","无法安全更新 settings.xml。","無法安全更新 settings.xml。"},
 {"the SD card. This cannot be undone.","SD 卡。此操作无法撤销。","SD 卡。此操作無法復原。"},
 {"then enable LSFG again.","然后再次启用 LSFG。","然後再次啟用 LSFG。"},
 {"Base games, updates, and DLC","基础游戏、更新和 DLC","基礎遊戲、更新和 DLC"},
 {"Current: ","当前：","目前："},
 {"Options","选项","選項"},
 {"Setting info","设置信息","設定資訊"},
 {"Installed to games folder","已安装到游戏文件夹","已安裝到遊戲資料夾"},
 {"Copy failed (SD space?)","复制失败（SD 空间？）","複製失敗（SD 空間？）"},
 {"Installed game content","已安装游戏内容","已安裝遊戲內容"},
 {"No installed content for this game","此游戏无已安装内容","此遊戲無已安裝內容"},
 {"No installed content found","未找到已安装内容","找不到已安裝內容"},
 {"General","常规","一般"},
 {"Manage game","管理游戏","管理遊戲"},
 {"Emulator","模拟器","模擬器"},
 {"Library","游戏库","遊戲庫"},
 {"Game menu","游戏菜单","遊戲選單"},
 {"NO COVER","无封面","無封面"},
 {"Icon","图标","圖示"},
 {"Name","名称","名稱"},
 {"Author","作者","作者"},
 {"Global settings","全局设置","全域設定"},
 {"Not set","未设置","未設定"},
 {"Configured","已配置","已設定"},
 {"Select an account","请先选择账户","請先選擇帳戶"},
 {"Title ID unavailable","标题 ID 不可用","標題 ID 無法使用"},
 {"No game selected","未选择游戏","未選擇遊戲"},
 {"Use icon","使用图标","使用圖示"},
 {"Edit","编辑","編輯"},
 {"Download graphics packs","下载图形包","下載圖形包"},
 {"Locations","位置","位置"},
 {"Select game folder","选择游戏文件夹","選擇遊戲資料夾"},
 {"A-Z","A-Z","A-Z"},
 {"Recently played","最近游玩","最近遊玩"},
 {"Recently added","最近添加","最近新增"},
 {"Add SMB network share","添加 SMB 网络共享","新增 SMB 網路共用"},
 {"Edit SMB network share","编辑 SMB 网络共享","編輯 SMB 網路共用"},
 {"Connect and save","连接并保存","連線並儲存"},
 {"Save changes","保存更改","儲存變更"},
 {"Manage installed content","管理已安装内容","管理已安裝內容"},
 {"Clear shader caches","清除着色器缓存","清除著色器快取"},
 {"Clear game settings","清除游戏设置","清除遊戲設定"},
 {"Favorite / collections","收藏 / 合集","最愛 / 收藏集"},
 {"Delete game (remove from SD)","删除游戏（从 SD 卡移除）","刪除遊戲（從 SD 卡移除）"},
 {"SD / USB / SMB","SD / USB / SMB","SD / USB / SMB"},
};
}
}
